data:
  augmentation:
    brightness_limit: 0.2
    contrast_limit: 0.2
    horizontal_flip: 0.5
    mixup_prob: 0.1
    mosaic_prob: 0.5
    rotation_limit: 15
    saturation_limit: 0.2
  detection:
    dataset_name: MinneApple
    test_split: 0.1
    train_split: 0.8
    val_split: 0.1
  quality_classification:
    class_weights:
    - 1.0
    - 1.5
    - 2.0
    classes:
    - good
    - minor_defect
    - major_defect
    dataset_name: AppleDefects
experiment:
  project_name: apple_detection_pipeline
  run_name: null
  use_tensorboard: true
  use_wandb: false
hardware:
  device: auto
  num_workers: 4
  pin_memory: true
logging:
  level: INFO
  log_interval: 10
  save_logs: true
model:
  detection:
    confidence_threshold: 0.3
    input_size:
    - 640
    - 640
    iou_threshold: 0.5
    max_detections: 100
    minneapple_model_variants:
    - models/minneapple/Original_augmented_best.pt
    - models/minneapple/Original_original_best.pt
    - models/minneapple/Small_augmented_best.pt
    - models/minneapple/Ground_augmented_best.pt
    model_name: yolov8n
    use_minneapple_weights: true
  quality_classification:
    dropout_rate: 0.2
    input_size:
    - 224
    - 224
    model_name: mobilenet_v3_small
    num_classes: 3
  tracking:
    feature_dim: 128
    iou_threshold: 0.3
    matching_threshold: 0.7
    max_age: 30
    min_hits: 3
paths:
  datasets:
    detection: datasets/detection
    quality: datasets/quality
  logs: logs
  models:
    detection: models/detection
    quality: models/quality
    tracking: models/tracking
  results: results
performance:
  detection:
    max_inference_time_ms: 100
    target_map50: 0.9
    target_map50_95: 0.75
  overall:
    max_memory_usage_gb: 2
    max_model_size_mb: 50
    target_fps: 15
  quality_classification:
    target_accuracy: 0.92
    target_f1_macro: 0.9
preprocessing:
  detection:
    letterbox: true
    normalize: true
  quality_classification:
    mean:
    - 0.485
    - 0.456
    - 0.406
    resize_method: bilinear
    std:
    - 0.229
    - 0.224
    - 0.225
training:
  detection:
    batch_size: 16
    device: auto
    epochs: 50
    learning_rate: 0.001
    optimizer: Adam
    patience: 20
    save_period: 10
    weight_decay: 0.0005
  quality_classification:
    batch_size: 32
    early_stopping_patience: 10
    epochs: 50
    gamma: 0.1
    learning_rate: 0.001
    optimizer: Adam
    step_size: 15
    weight_decay: 0.0001
